.PHONY: install install-dev install-locked lock lint format typecheck test test-cov reproduce clean

PYTHON ?= python

install:
	$(PYTHON) -m pip install -e .

install-dev:
	$(PYTHON) -m pip install -e ".[dev,docs]"
	pre-commit install

# Reproduce the exact pinned environment recorded in requirements/lock.txt
# (see that file's header), then install wfcrc itself without re-resolving
# its dependencies.
install-locked:
	$(PYTHON) -m pip install -r requirements/lock.txt
	$(PYTHON) -m pip install --no-deps -e .

# Regenerate requirements/lock.txt from the currently active environment.
# Run this after deliberately upgrading a dependency, from an environment
# built via `make install-dev` (dev + docs extras installed).
lock:
	echo "# Generated by \`make lock\` (pip freeze --exclude-editable) — do not hand-edit." > requirements/lock.txt
	echo "# Full pinned dependency closure for \`pip install -e \".[dev,docs]\"\`." >> requirements/lock.txt
	echo "# See docs/reproducibility.md for what this file is for and how to use it." >> requirements/lock.txt
	$(PYTHON) -m pip freeze --exclude-editable | sort -f >> requirements/lock.txt

lint:
	ruff check wfcrc tests scripts
	black --check wfcrc tests scripts

format:
	ruff check --fix wfcrc tests scripts
	black wfcrc tests scripts

typecheck:
	mypy wfcrc scripts

test:
	pytest --no-cov

test-cov:
	pytest

# MS5: re-run the (synthetic) reference experiment and diff its manifest
# against the committed golden file (tests/fixtures/reproduce_golden.json)
# within tolerance (Implementation Blueprint §17, MS5 spec C2 item 5).
# Use `python scripts/reproduce.py --write-golden` to regenerate the golden
# file after a deliberate change to the reference experiment itself.
reproduce:
	$(PYTHON) scripts/reproduce.py

clean:
	find . -type d -name '__pycache__' -exec rm -rf {} +
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage
