.PHONY: install install-dev install-locked lock lint format typecheck test test-cov reproduce clean

PYTHON ?= python

install:
	$(PYTHON) -m pip install -e .

install-dev:
	$(PYTHON) -m pip install -e ".[dev,docs]"
	pre-commit install

# Reproduce the exact pinned environment recorded in requirements/lock.txt
# (see that file's header), then install wfcrc itself without re-resolving
# its dependencies.
install-locked:
	$(PYTHON) -m pip install -r requirements/lock.txt
	$(PYTHON) -m pip install --no-deps -e .

# Regenerate requirements/lock.txt from the currently active environment.
# Run this after deliberately upgrading a dependency, from an environment
# built via `make install-dev` (dev + docs extras installed).
lock:
	echo "# Generated by \`make lock\` (pip freeze --exclude-editable) — do not hand-edit." > requirements/lock.txt
	echo "# Full pinned dependency closure for \`pip install -e \".[dev,docs]\"\`." >> requirements/lock.txt
	echo "# See docs/reproducibility.md for what this file is for and how to use it." >> requirements/lock.txt
	$(PYTHON) -m pip freeze --exclude-editable | sort -f >> requirements/lock.txt

lint:
	ruff check wfcrc tests
	black --check wfcrc tests

format:
	ruff check --fix wfcrc tests
	black wfcrc tests

typecheck:
	mypy wfcrc

test:
	pytest --no-cov

test-cov:
	pytest

# MS1 stub: later milestones wire this to re-run a reference experiment and
# diff its metrics against a stored golden file (Implementation Blueprint §17).
reproduce:
	@echo "make reproduce: no experiments implemented yet (MS1 scope is infrastructure only)."

clean:
	find . -type d -name '__pycache__' -exec rm -rf {} +
	rm -rf .pytest_cache .mypy_cache .ruff_cache htmlcov .coverage
