"""Shared figure-rendering plumbing for :mod:`wfcrc.visualization.plots` (M14).

Per the MS5 Implementation Specification (C1 items 4-9): every figure is a
vector file (`.pdf`/`.svg`) plus a **data sidecar** (`.csv`) that equals the
exact data used to render it, so a figure can be regenerated byte-for-byte
from a metrics manifest with no algorithm re-run. This module supplies the
two data structures the spec names (`FigureSpec`, `FigureFile`) and the
deterministic save/hash/sidecar plumbing every `plot_*` function in
:mod:`wfcrc.visualization.plots` shares, so that module only contains
per-figure axis/series logic.

**Determinism.** `matplotlib`'s default PDF/SVG output embeds a creation
timestamp and (for SVG) per-element ids derived from Python object ids,
neither of which is reproducible across processes. This module fixes both:
`_DETERMINISTIC_METADATA` blanks the timestamp/creator/producer fields
`savefig` accepts, and `_SVG_HASHSALT` pins `matplotlib`'s SVG id generator
to a fixed salt (via `rcParams["svg.hashsalt"]`) instead of a per-process
random one. Two calls to :func:`render_figure` with identical `fig` content
and `spec` therefore produce byte-identical output (see
`tests/unit/visualization/test_base.py::test_render_figure_is_byte_deterministic`).
"""

from __future__ import annotations

import csv
import io
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

import matplotlib

matplotlib.use("Agg")  # headless backend; must precede the pyplot import below
import matplotlib.pyplot as plt
from matplotlib.axes import Axes
from matplotlib.figure import Figure

from wfcrc.utils.io import atomic_write, content_hash, ensure_dir

__all__ = ["FigureFile", "FigureSpec", "render_figure"]

#: Fixed salt for `matplotlib`'s SVG element-id generator (`rcParams["svg.hashsalt"]`),
#: so SVG output does not embed a per-process-random id and is byte-reproducible.
_SVG_HASHSALT = "wfcrc-deterministic-figures"

#: `savefig(..., metadata=...)` overrides that blank out timestamp/producer
#: fields matplotlib would otherwise embed non-deterministically.
_DETERMINISTIC_METADATA: dict[Literal["pdf", "svg"], dict[str, str | None]] = {
    "pdf": {"CreationDate": None, "Creator": "", "Producer": ""},
    "svg": {"Date": None, "Creator": ""},
}

# Batch experiment sweeps/tests legitimately create many figures in one
# process; `render_figure` always closes each one immediately, so the
# "too many open figures" memory warning does not apply here.
matplotlib.rcParams["figure.max_open_warning"] = 0

FigureFormat = Literal["pdf", "svg"]


@dataclass(frozen=True)
class FigureSpec:
    """Deterministic styling/format parameters shared by every figure.

    Attributes:
        format: Output vector format, `"pdf"` or `"svg"`.
        dpi: Rendering resolution (only affects raster elements embedded in
            the vector output, e.g. `imshow` heatmaps).
        figsize: `(width, height)` in inches.
    """

    format: FigureFormat = "pdf"
    dpi: int = 150
    figsize: tuple[float, float] = (6.0, 4.0)

    def __post_init__(self) -> None:
        """Validate `format`/`dpi`.

        Raises:
            ValueError: If `format` is not `"pdf"`/`"svg"`, or `dpi <= 0`.
        """
        if self.format not in ("pdf", "svg"):
            raise ValueError(f"format must be 'pdf' or 'svg', got {self.format!r}")
        if self.dpi <= 0:
            raise ValueError(f"dpi must be > 0, got {self.dpi}")


@dataclass(frozen=True)
class FigureFile:
    """A rendered figure plus its reproducibility sidecar.

    Attributes:
        path: Path to the vector figure file (`.pdf`/`.svg`).
        sidecar_path: Path to the `.csv` data sidecar (exactly the data used
            to render `path`).
        source_hash: Content hash of the data used to render this figure,
            embedded in the sidecar's header comment for provenance.
    """

    path: Path
    sidecar_path: Path
    source_hash: str


def new_figure(spec: FigureSpec) -> tuple[Figure, Axes]:
    """Create a `(Figure, Axes)` pair with this project's deterministic style.

    Args:
        spec: Format/size/dpi parameters for the new figure.

    Returns:
        A fresh `(fig, ax)` pair; the caller draws onto `ax` and then calls
        :func:`render_figure` with the same `fig`.
    """
    matplotlib.rcParams["svg.hashsalt"] = _SVG_HASHSALT
    fig, ax = plt.subplots(figsize=spec.figsize, dpi=spec.dpi)
    return fig, ax


def _write_csv_sidecar(
    sidecar_path: Path, header: list[str], rows: list[list[Any]], source_hash: str
) -> None:
    """Atomically write a CSV sidecar with a provenance header comment.

    Args:
        sidecar_path: Destination `.csv` path.
        header: Column names (first data row).
        rows: Data rows, each the same length as `header`.
        source_hash: This figure's `FigureFile.source_hash`, written as a
            leading `#`-comment line for provenance.
    """
    buffer = io.StringIO()
    buffer.write(f"# source_hash={source_hash}\n")
    writer = csv.writer(buffer, lineterminator="\n")
    writer.writerow(header)
    writer.writerows(rows)
    atomic_write(sidecar_path, buffer.getvalue().encode("utf-8"))


def render_figure(
    fig: Figure,
    *,
    data: Any,
    out_dir: str | Path,
    stem: str,
    spec: FigureSpec,
    sidecar_header: list[str],
    sidecar_rows: list[list[Any]],
) -> FigureFile:
    """Render `fig` to a deterministic vector file plus a CSV data sidecar.

    Args:
        fig: The fully drawn figure (caller is responsible for all axis
            content; this function only saves and closes it).
        data: The exact JSON-serializable data used to draw `fig` (arrays
            are fine; see :func:`wfcrc.utils.io.content_hash`), hashed for
            `FigureFile.source_hash`.
        out_dir: Destination directory (created if missing).
        stem: Filename stem shared by the figure and its sidecar (e.g.
            `"f1_risk_vs_alpha"` yields `f1_risk_vs_alpha.pdf` +
            `f1_risk_vs_alpha.csv`).
        spec: Format/dpi/figsize parameters.
        sidecar_header: CSV column names for the sidecar.
        sidecar_rows: CSV data rows for the sidecar (same data as `data`,
            flattened to rows — this is what "sidecar equals source
            metrics" means concretely).

    Returns:
        The resulting :class:`FigureFile`.

    Raises:
        OSError: On filesystem failures.
        TypeError: If `data` is not JSON-serializable.
    """
    directory = ensure_dir(out_dir)
    source_hash = content_hash(data)

    fig_path = directory / f"{stem}.{spec.format}"
    buffer = io.BytesIO()
    fig.savefig(
        buffer,
        format=spec.format,
        metadata=_DETERMINISTIC_METADATA[spec.format],
    )
    plt.close(fig)
    atomic_write(fig_path, buffer.getvalue())

    sidecar_path = directory / f"{stem}.csv"
    _write_csv_sidecar(sidecar_path, sidecar_header, sidecar_rows, source_hash)

    return FigureFile(path=fig_path, sidecar_path=sidecar_path, source_hash=source_hash)
